# Generated by Django 4.2.2 on 2024-05-26 15:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Inspiration', 'Inspiration'), ('Popular', 'Popular'), ('Latest_post', 'Latest_post'), ('Recent', 'Recent'), ('Editor_pick', 'Editor_pick'), ('main_post', 'main_post'), ('Tranding', 'Tranding')], max_length=200),
        ),
    ]
