# Generated by Django 4.2.2 on 2024-05-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_main_post_alter_post_content_alter_post_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Inspiration', 'Inspiration'), ('Recent', 'Recent'), ('Popular', 'Popular'), ('Latest_post', 'Latest_post'), ('main_post', 'main_post'), ('Editor_pick', 'Editor_pick'), ('Tranding', 'Tranding')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], max_length=100),
        ),
    ]
