# Generated by Django 4.2.2 on 2024-05-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_post_category_alter_post_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Latest_post', 'Latest_post'), ('Inspiration', 'Inspiration'), ('Tranding', 'Tranding'), ('Popular', 'Popular'), ('main_post', 'main_post'), ('Recent', 'Recent'), ('Editor_pick', 'Editor_pick')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], max_length=100),
        ),
    ]
