# Generated by Django 4.2.2 on 2024-05-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_post_category_alter_post_section_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('main_post', 'main_post'), ('Tranding', 'Tranding'), ('Inspiration', 'Inspiration'), ('Recent', 'Recent'), ('Latest_post', 'Latest_post'), ('Popular', 'Popular'), ('Editor_pick', 'Editor_pick')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], max_length=100),
        ),
    ]
