# Generated by Django 4.2.2 on 2024-05-31 15:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_post_author_image_alter_post_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('main_post', 'main_post'), ('Tranding', 'Tranding'), ('Recent', 'Recent'), ('Popular', 'Popular'), ('Editor_pick', 'Editor_pick'), ('Inspiration', 'Inspiration'), ('Latest_post', 'Latest_post')], max_length=200),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
            ],
        ),
        migrations.CreateModel(
            name='Political',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=400, null=True, unique=True)),
                ('status', models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], max_length=100)),
                ('section', models.CharField(choices=[('main_post', 'main_post'), ('Tranding', 'Tranding'), ('Recent', 'Recent'), ('Popular', 'Popular'), ('Editor_pick', 'Editor_pick'), ('Inspiration', 'Inspiration'), ('Latest_post', 'Latest_post')], max_length=200)),
                ('main_post', models.BooleanField(default=False)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
        ),
    ]
