# Generated by Django 4.2.2 on 2024-05-31 15:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_categorys_alter_post_section_tags_political'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryfinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='political',
            name='Feature_image',
            field=models.ImageField(upload_to='media/Political'),
        ),
        migrations.AlterField(
            model_name='political',
            name='section',
            field=models.CharField(choices=[('Inspiration', 'Inspiration'), ('Popular', 'Popular'), ('Editor_pick', 'Editor_pick'), ('Recent', 'Recent'), ('Tranding', 'Tranding'), ('main_post', 'main_post'), ('Latest_post', 'Latest_post')], max_length=200),
        ),
        migrations.AlterField(
            model_name='political',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Inspiration', 'Inspiration'), ('Popular', 'Popular'), ('Editor_pick', 'Editor_pick'), ('Recent', 'Recent'), ('Tranding', 'Tranding'), ('main_post', 'main_post'), ('Latest_post', 'Latest_post')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], max_length=100),
        ),
        migrations.CreateModel(
            name='Tagsfinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
            ],
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_image', models.ImageField(upload_to='media/Finance')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=400, null=True, unique=True)),
                ('status', models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], max_length=100)),
                ('section', models.CharField(choices=[('Inspiration', 'Inspiration'), ('Popular', 'Popular'), ('Editor_pick', 'Editor_pick'), ('Recent', 'Recent'), ('Tranding', 'Tranding'), ('main_post', 'main_post'), ('Latest_post', 'Latest_post')], max_length=200)),
                ('main_post', models.BooleanField(default=False)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
        ),
    ]
