# Generated by Django 4.2.2 on 2024-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_categoryfinance_alter_political_feature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='section',
            field=models.CharField(choices=[('Latest_post', 'Latest_post'), ('Tranding', 'Tranding'), ('main_post', 'main_post'), ('Popular', 'Popular'), ('Inspiration', 'Inspiration'), ('Recent', 'Recent'), ('Editor_pick', 'Editor_pick')], max_length=200),
        ),
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='political',
            name='section',
            field=models.CharField(choices=[('Latest_post', 'Latest_post'), ('Tranding', 'Tranding'), ('main_post', 'main_post'), ('Popular', 'Popular'), ('Inspiration', 'Inspiration'), ('Recent', 'Recent'), ('Editor_pick', 'Editor_pick')], max_length=200),
        ),
        migrations.AlterField(
            model_name='political',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Latest_post', 'Latest_post'), ('Tranding', 'Tranding'), ('main_post', 'main_post'), ('Popular', 'Popular'), ('Inspiration', 'Inspiration'), ('Recent', 'Recent'), ('Editor_pick', 'Editor_pick')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], max_length=100),
        ),
    ]
